export const uiCopy = {
  ru: {
    app: {
      title: "Кыргызча",
      levelLabel: "Кыргызский K0/K1",
      settings: "Настройки",
      navigationLabel: "Основная навигация",
      tabs: {
        home: "Главная",
        learn: "Учиться",
        practice: "Практика",
        games: "Игры",
        profile: "Профиль",
      },
    },
    common: {
      check: "Проверить",
      clear: "Очистить",
      continue: "Продолжить",
      openLesson: "Открыть урок",
      lesson: "Урок",
      start: "Старт",
      today: "Сегодня",
      ready: "Готово",
      correct: "Верно",
      corrected: "Исправлено",
      retry: "Повторить",
      tryAgain: "Попробовать ещё раз",
      answer: "Ответ",
      correctAnswer: "Правильный ответ",
      yourAnswer: "Ваш ответ",
      again: "Ещё раз",
      comingSoonTitle: "Этот формат скоро появится",
      comingSoonBody: "Продолжайте урок, это задание откроется позже.",
    },
    home: {
      heroEyebrow: "Сегодня",
      heroTitle: "Начните говорить по-кыргызски",
      heroBody: "Короткие уроки, живые фразы и спокойный ежедневный прогресс.",
      continueLesson: "Продолжить урок",
      lessonsReady: "Готовые уроки",
      practicePoints: "Очки практики",
      progressTitle: "Ваш прогресс",
      progressDescription: (completion: number) =>
        `${completion}% текущего маршрута уже пройдено. Двигайтесь короткими шагами.`,
      currentLesson: "Текущий урок",
      openLesson: "Открыть урок",
    },
    learn: {
      title: "Маршрут",
      description:
        "Идите от первых звуков к простым фразам на каждый день.",
      startBadge: "Старт",
    },
    games: {
      title: "Игры",
      body: "Короткие игры будут закреплять слова и фразы из уроков.",
      chips: ["Звуки", "Быстрый выбор", "Порядок слов", "Память"],
    },
    profile: {
      title: "Профиль",
      body: "Здесь будут маршрут обучения, дневная цель, история и настройки.",
      chips: ["Прогресс", "Маршрут", "Дневная цель", "История"],
    },
    lesson: {
      steps: [
        { id: "story", label: "Ситуация", sectionId: "lesson-story" },
        { id: "goals", label: "Цель", sectionId: "lesson-goals" },
        { id: "words", label: "Слова", sectionId: "lesson-words" },
        { id: "dialogue", label: "Диалог", sectionId: "lesson-dialogue" },
        { id: "breakdown", label: "Разбор", sectionId: "lesson-breakdown" },
        { id: "grammar", label: "Грамматика", sectionId: "lesson-grammar" },
        { id: "practice", label: "Практика", sectionId: "lesson-practice" },
        { id: "game", label: "Игра", sectionId: "lesson-game" },
        { id: "speaking", label: "Речь", sectionId: "lesson-speaking" },
        { id: "roleplay", label: "Диалог", sectionId: "lesson-roleplay" },
        { id: "review", label: "Итог", sectionId: "lesson-review" },
      ],
      progressAria: "Прогресс урока",
      nextStep: "Далее",
      heroBody: "Короткий урок для повседневного кыргызского.",
      storyDescription: "Сначала контекст, затем новые слова.",
      goalsTitle: "После урока вы сможете",
      goalsDescription: "2-3 понятных результата.",
      vocabularyTitle: "Главные слова",
      vocabularyDescription: "Они встретятся в диалоге и практике.",
      readingTitle: "Текст",
      readingDescription: "Короткое чтение.",
      breakdownTitle: "Как это устроено",
      breakdownDescription: "Посмотрите на кусочки перед практикой.",
      usefulChunk: "Полезный кусок",
      grammarDescription: "Почему фраза работает.",
      practiceTitle: "Проверьте себя",
      practiceDescription: "Короткая серия заданий.",
      gameBody: "Быстрое повторение слов из урока.",
      speakingAction: "Попробовать вслух",
      roleplayTitle: "Тренировка ситуации",
      roleplayBody: "Используйте слова урока в коротком безопасном диалоге.",
      reviewEyebrow: "Повторение",
      reviewTitle: "Итог урока",
      practiceSummaryTitle: "Практика",
      completeLesson: "Завершить урок",
      lessonComplete: "Урок завершён",
      practiceResultCompleteWithCorrections: (
        completed: number,
        correct: number,
        corrected: number,
      ) =>
        `Вы сделали ${completed} задания, сразу ответили верно на ${correct} и исправили ${corrected}.`,
      practiceResultNeedsReview: (completed: number, remaining: number) =>
        `Вы сделали ${completed} задания. Нужно повторить: ${remaining}.`,
      practiceResultComplete: (correct: number, total: number) =>
        `Практика завершена: ${correct} из ${total} верно.`,
      practiceResultInProgress: (completed: number, total: number, correct: number) =>
        `Готово: ${completed} из ${total}. Верно: ${correct}.`,
      practiceResultEmpty: "Сделайте практику, чтобы увидеть итог.",
      practiceNextReviewFirst: "Лучше повторить ошибки перед следующим шагом.",
      practiceNextComplete: "Повторите фразы ещё раз и завершите урок.",
      practiceNextPreparing: "Практика для этого урока готовится.",
      practiceNextInProgress:
        "Закончите карточку практики и вернитесь к итогу.",
    },
    audio: {
      listen: "Слушать",
      soon: "Скоро",
      wordAria: "Слушать слово",
      phraseAria: "Слушать фразу",
      textAria: "Слушать текст",
      unavailableSuffix: "скоро",
      playError: "Не удалось включить аудио.",
    },
    exercise: {
      almost: "Почти.",
      wordInputPlaceholder: "Введите слово",
      answerInputPlaceholder: "Введите ответ",
      correctionInputPlaceholder: "Введите исправленную фразу",
      sentenceBuilderEmpty: "Нажимайте слова по порядку",
      sentenceBuilderAvailableWords: "Доступные слова",
      addTile: (text: string) => `Добавить ${text}`,
      removeTile: (text: string) => `Убрать ${text}`,
      fixPhrase: "Исправьте фразу",
      whatIsCorrect: "Как будет правильно?",
      correctVersion: "Правильный вариант",
      correctionHint: "Пишите коротко и точно по-кыргызски.",
      matchIntroTitle: "Соедините пары",
      matchIntroBody: "Выберите одну фразу и одно значение.",
      matchEmpty: "Нажмите элементы, чтобы соединить пару",
      matchLeft: "Фразы",
      matchRight: "Значения",
      remove: "Убрать",
      reset: "Сбросить",
    },
    practice: {
      progressAria: "Прогресс практики",
      complete: "Практика завершена",
      preparing: "Практика готовится",
      titleIdle: "Делайте по одному заданию",
      titleInProgress: "Хорошо, продолжайте",
      completedLabel: "Готово",
      step: (current: number, total: number) => `Практика ${current} из ${total}`,
      completeCanContinue: "Можно идти дальше",
      completeScore: (correct: number, total: number) =>
        `Верно: ${correct} из ${total}. Держите фразу в памяти.`,
      missedTitle: "Повторить ошибки",
      missedHeading: "Быстро закрепим",
      missedCount: (total: number, remaining: number) =>
        `Ошибок: ${total}. Осталось повторить: ${remaining}.`,
      continueAnyway: "Продолжить сейчас",
      retryFeedback: "Почти. Посмотрите на ответ и попробуйте ещё раз.",
      repeatFillBlank: "Введите ответ ещё раз",
      repeatSentence: "Соберите фразу ещё раз",
      correctedCount: (count: number) =>
        `Исправлено ошибок: ${count}. Можно идти дальше.`,
      savedPrevious:
        "Прошлая практика сохранена. Закончите текущие задания, чтобы обновить урок.",
    },
    reviewQueue: {
      filters: {
        needs_review: "Повторить",
        corrected: "Исправлено",
        all: "Все",
      },
      heroEyebrow: "Практика",
      heroTitle: "Повторите слабые места",
      heroBody: "Возвращайтесь к ошибкам короткими спокойными подходами.",
      summaryAria: "Сводка практики",
      completed: "Готово",
      missed: "Ошибки",
      needsReview: "Повторить",
      corrected: "Исправлено",
      emptyTitle: "Пока нечего повторять",
      emptyBody:
        "Сейчас всё чисто. После урока ошибки появятся здесь для короткого повтора.",
      toLessons: "К урокам",
      queueEyebrow: "Очередь повтора",
      queueTitle: "Закрепить",
      needsBadge: (count: number) => `Нужно: ${count}`,
      filtersAria: "Фильтры повтора",
      allClearTitle: "Повтор завершён",
      allClearBody: "Текущие ошибки исправлены. Продолжайте.",
      emptyFilterTitle: {
        needs_review: "Сейчас нечего повторять",
        corrected: "Пока нет исправленных",
        all: "Пока нечего повторять",
      },
      emptyFilterBody: {
        needs_review: "Всё чисто. Исправленные ответы остаются в истории.",
        corrected: "Исправленные ответы появятся здесь после повтора ошибок.",
        all: "После уроков ошибки появятся здесь для быстрого повтора.",
      },
      fallbackLessonTitle: "Повтор урока",
      cardNeedsReview: "Нужно повторить",
      cardCorrectedDescription: "Вы уже закрепили этот ответ.",
      cardNeedsReviewDescription: "Короткий повтор поможет запомнить.",
      readyBadge: "Готово",
      correctedBody: "Этот ответ закреплён. Продолжайте.",
      retryCorrect: "Исправлено",
      openLessonForReview: "Откройте урок для повтора",
      unsupportedReview:
        "Этот формат пока удобнее повторять внутри урока.",
      repeatInLesson: "Повторить в уроке",
    },
  },
} as const;

export const defaultUiLanguage = "ru";
export const defaultUiCopy = uiCopy[defaultUiLanguage];

export type UiLanguage = keyof typeof uiCopy;
export type UiCopy = (typeof uiCopy)[UiLanguage];
